[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NorESM2.2"
authors = [{name = "Lina", email = "lina.boljka@uib.no"}]
dynamic = ["version", "description"]
